NAME         := TIOCLNT
DESCRIPTION  := "Project Ti-0 CLIENT PRGM"
ICON         := icon.png
APPVAR = YES
COMPRESSED = YES
ARCHIVED = YES
LIBS = graphx keypadc


# Source code directory
SRC := src

# Include CEDev common makefile rules
include $(shell cedev-config --makefile)